@startuml
class Screen{
+void Screen(): construtor
+void showMessage():
}
class PPDOS{
    +void PPDOS(): construtor
    +void inicializeSystem()
    +void makeOpenDirectoryFile()
    +void makeChargeDataFile()
    +void makeCombineDataFile()
    +void makeDataClean()
    +void makeDataExploratoryAnalysis()
    +void makeDataViz()
    +void startResultExport()   
    +void showMessage()
}
class MainPPDOS{
    +void MainPPDOS(): construtor
    +void activatePPDOS()    
}
abstract class Transaction{
    +void execute()
    +void concludeOperation()
}
class MakeOpenDirectory{
    +void MakeOpenDirectory(): construtor
    +void execute()
    +void concludeOperation()
   
}
class MakeFileCharge{
    +void MakeFileCharge(): construtor
    +void execute()
    +void concludeOperation()
    
}
class MakeFileCombiner{
    +void MakeFileCombiner(): construtor
    +void execute()
    +void concludeOperation()
 
}

class MakeDataClean{
    +void MakeDataClean(): construtor
    +void execute()
    +void concludeOperation()
   
}

class MakeExploratoryAnalysis{
    +void MakeExploratoryAnalysis(): construtor
    +void execute()
    +void concludeOperation()
   
}
class MakeDataViz{
    +void MakeDataViz(): construtor
    +void execute()
    +void concludeOperation()
    
}
class MakeDataOptimization{
    -RGO
    -STO
    -skin
    -RecoveryFactor
    +void MakeDataOptimizationz(): construtor
    +void execute()
    +void concludeOperation()
   
}

class MakeOpenFolder{
    +void MakeOpenFolder(): construtor
    +void execute()
    +void concludeOperation()
    
}
class MakeFileExport{
    +void MakeFileExport(): construtor
    +void execute()
    +void concludeOperation()
  
}

class Mouser{
    +Mouser(): construtor
    +void sendInput()
}
@enduml