@startuml
class  MainPPDOS 
class  PPDOS
class  Screen
class  Mouser
abstract class Transaction
class  MakeOpenDirectory
class  MakeDataCombiner
class  MakeDataClean
class  MakeExploratoryAnalysis
class  MakeDataOptimization
class  MakeOpenFolder
class  MakeFileExport

PPDOS *-- MainPPDOS
PPDOS *-- Screen
PPDOS *-- Mouser
PPDOS --> Transaction: "executes"
Transaction <|-- MakeOpenDirectory
Transaction <|-- MakeDataCombiner
Transaction <|-- MakeDataClean
Transaction <|-- MakeExploratoryAnalysis
Transaction <|-- MakeDataOptimization
Transaction <|-- MakeOpenFolder
Transaction <|-- MakeFileExport
Transaction --> Screen: "shows messages and data visualization"
@enduml