@startuml
actor User as Foo1
boundary PPDOSMain as Foo2
control PPDOS as Foo3
Foo3 -> Screen: showMessage(): show message to press data file charge button
Screen --> Foo1: press data file charge button
destroy Screen
Foo1 -> Mouser: press data file charge button
Mouser -> Foo2: sendImput()
destroy Mouser
Foo2 -> Foo3: processing
alt successful case in  data file charge 
    Foo3 -> Transaction: openDirectoryFolder()
    Transaction -> MakeFileCharger: execute()
    MakeFileCharger --> Foo3:concludeOperation()
    destroy MakeFileCharger
    Foo3 -> Screen: showMessage() 
    Screen --> Foo1: success data file charge message
    destroy Screen
else failure of data file charge
    MakeFileCharger -> Exception: failure
    break Exception 
        Exception  --> Foo3: Exception Handling 
        destroy Exception
    end 
    Foo3 -> Screen: showMessage()
    Screen --> Foo1: Error message in data file charge
    destroy Screen
end
@enduml